### ISSUE TITLE
--flag=false parses as string instead of boolean

### ISSUE THREAD

**Issue by toddself** [jbucaran/getopts#17]
If you set up a flag and use `--flag=false` instead of `--no-flag` you get back a string `'false'` instead of the boolean `false`.

**Comment by toddself** [comment]
A fix: https://github.com/jbucaran/parsec/pull/18

**Comment by jbucaran** [comment]
@toddself Thanks for the fix. I think we can close here.

Please see #19 to understand why I renamed the repository. 👋
